In [49]:
import numpy as np
import pandas as pd
date = pd.read_csv('orders.csv')

In [5]:
date.head()

         date  product_id  city_id  orders
0  2019-12-10        5628       25       3
1  2018-08-15        3646       14     157
2  2018-10-23        1859       25       1
3  2019-08-17        7292       25       1
4  2019-01-06        4344       25       3

In [46]:
time.head()

0   2013-12-15 00:50:00
1   2014-04-29 23:40:00
2   2012-12-30 00:21:00
3   2014-11-28 00:31:00
4   2013-10-26 23:11:00
Name: date, dtype: datetime64[ns]

In [7]:
date.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   date        1000 non-null   object
 1   product_id  1000 non-null   int64
 2   city_id     1000 non-null   int64
 3   orders      1000 non-null   int64
dtypes: int64(3), object(1)
memory usage: 31.4+ KB

In [47]:
time.info()

<class 'pandas.core.series.Series'>
RangeIndex: 1000 entries, 0 to 999
Series name: date
Non-Null Count  Dtype
--------------  -----
1000 non-null   datetime64[ns]
dtypes: datetime64[ns](1)
memory usage: 7.9 KB

working with dates

In [9]:
date['date']=pd.to_datetime(date['date'])

In [10]:
date.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   date        1000 non-null   datetime64[ns]
 1   product_id  1000 non-null   int64
 2   city_id     1000 non-null   int64
 3   orders      1000 non-null   int64
dtypes: datetime64[ns](1), int64(3)
memory usage: 31.4 KB

In [11]:
date['date_year']=date['date'].dt.year
date.head()

        date  product_id  city_id  orders  date_year
0 2019-12-10        5628       25       3       2019
1 2018-08-15        3646       14     157       2018
2 2018-10-23        1859       25       1       2018
3 2019-08-17        7292       25       1       2019
4 2019-01-06        4344       25       3       2019

In [12]:
date['date_month']=date['date'].dt.month
date.head()

        date  product_id  city_id  orders  date_year  date_month
0 2019-12-10        5628       25       3       2019          12
1 2018-08-15        3646       14     157       2018           8
2 2018-10-23        1859       25       1       2018          10
3 2019-08-17        7292       25       1       2019           8
4 2019-01-06        4344       25       3       2019           1

In [13]:
date['date_month_name']=date['date'].dt.month_name()
date.head()

,date,product_id,city_id,orders,date_year,date_month,date_month_name
0,2019-12-10,5628,25,3,2019,12,December
1,2018-08-15,3646,14,157,2018,8,August
2,2018-10-23,1859,25,1,2018,10,October
3,2019-08-17,7292,25,1,2019,8,August
4,2019-01-06,4344,25,3,2019,1,January

In [14]:
date['date_day']=date['date'].dt.day
date.head()

,date,product_id,city_id,orders,date_year,date_month,date_month_name,date_day
0,2019-12-10,5628,25,3,2019,12,December,10
1,2018-08-15,3646,14,157,2018,8,August,15
2,2018-10-23,1859,25,1,2018,10,October,23
3,2019-08-17,7292,25,1,2019,8,August,17
4,2019-01-06,4344,25,3,2019,1,January,6

In [15]:
date['date_dow']=date['date'].dt.dayofweek
date.head()

,date,product_id,city_id,orders,date_year,date_month,date_month_name,date_day,date_dow
0,2019-12-10,5628,25,3,2019,12,December,10,1
1,2018-08-15,3646,14,157,2018,8,August,15,2
2,2018-10-23,1859,25,1,2018,10,October,23,1
3,2019-08-17,7292,25,1,2019,8,August,17,5
4,2019-01-06,4344,25,3,2019,1,January,6,6

In [16]:
date['date_dow_dayname']=date['date'].dt.day_name()
date.drop(columns=['product_id','city_id','orders']).head()

,date,date_year,date_month,date_month_name,date_day,date_dow,date_dow_dayname
0,2019-12-10,2019,12,December,10,1,Tuesday
1,2018-08-15,2018,8,August,15,2,Wednesday
2,2018-10-23,2018,10,October,23,1,Tuesday
3,2019-08-17,2019,8,August,17,5,Saturday
4,2019-01-06,2019,1,January,6,6,Sunday

In [17]:
#is the day weekend
date['date_is_weekend']=np.where(date['date_dow_dayname'].isin(['Saturday','Sunday']),1,0)
date.drop(columns=['product_id','city_id','orders']).head()

,date,date_year,date_month,date_month_name,date_day,date_dow,date_dow_dayname,date_is_weekend
0,2019-12-10,2019,12,December,10,1,Tuesday,0
1,2018-08-15,2018,8,August,15,2,Wednesday,0
2,2018-10-23,2018,10,October,23,1,Tuesday,0
3,2019-08-17,2019,8,August,17,5,Saturday,1
4,2019-01-06,2019,1,January,6,6,Sunday,1

In [18]:
date['date_week'] = date['date'].dt.isocalendar().week
date.head()

,date,product_id,city_id,orders,date_year,date_month,date_month_name,date_day,date_dow,date_dow_dayname,date_is_weekend,date_week
0,2019-12-10,5628,25,3,2019,12,December,10,1,Tuesday,0,50
1,2018-08-15,3646,14,157,2018,8,August,15,2,Wednesday,0,33
2,2018-10-23,1859,25,1,2018,10,October,23,1,Tuesday,0,43
3,2019-08-17,7292,25,1,2019,8,August,17,5,Saturday,1,33
4,2019-01-06,4344,25,3,2019,1,January,6,6,Sunday,1,1

In [19]:
date['quarter'] = date['date'].dt.quarter
date.drop(columns=['product_id','city_id',	'orders'	]).head()

,date,date_year,date_month,date_month_name,date_day,date_dow,date_dow_dayname,date_is_weekend,date_week,quarter
0,2019-12-10,2019,12,December,10,1,Tuesday,0,50,4
1,2018-08-15,2018,8,August,15,2,Wednesday,0,33,3
2,2018-10-23,2018,10,October,23,1,Tuesday,0,43,4
3,2019-08-17,2019,8,August,17,5,Saturday,1,33,3
4,2019-01-06,2019,1,January,6,6,Sunday,1,1,1

In [20]:
date['date_semester']=np.where(date['quarter'].isin([1,2]),1,2)
date.head()

,date,product_id,city_id,orders,date_year,date_month,date_month_name,date_day,date_dow,date_dow_dayname,date_is_weekend,date_week,quarter,date_semester
0,2019-12-10,5628,25,3,2019,12,December,10,1,Tuesday,0,50,4,2
1,2018-08-15,3646,14,157,2018,8,August,15,2,Wednesday,0,33,3,2
2,2018-10-23,1859,25,1,2018,10,October,23,1,Tuesday,0,43,4,2
3,2019-08-17,7292,25,1,2019,8,August,17,5,Saturday,1,33,3,2
4,2019-01-06,4344,25,3,2019,1,January,6,6,Sunday,1,1,1,1

In [21]:
import datetime

today = datetime.datetime.today()

today

datetime.datetime(2026, 7, 28, 19, 20, 51, 966134)

In [22]:
today-date['date']

0     2422 days 19:20:51.966134
1     2904 days 19:20:51.966134
2     2835 days 19:20:51.966134
3     2537 days 19:20:51.966134
4     2760 days 19:20:51.966134
                 ...
995   2850 days 19:20:51.966134
996   2791 days 19:20:51.966134
997   2639 days 19:20:51.966134
998   2704 days 19:20:51.966134
999   2478 days 19:20:51.966134
Name: date, Length: 1000, dtype: timedelta64[ns]

In [24]:
(today-date['date']).dt.days

0      2422
1      2904
2      2835
3      2537
4      2760
       ...
995    2850
996    2791
997    2639
998    2704
999    2478
Name: date, Length: 1000, dtype: int64

In [27]:
time.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   date    1000 non-null   object
 1   msg     1000 non-null   object
dtypes: object(2)
memory usage: 15.8+ KB

In [30]:
time.head()

0   2013-12-15 00:50:00
1   2014-04-29 23:40:00
2   2012-12-30 00:21:00
3   2014-11-28 00:31:00
4   2013-10-26 23:11:00
Name: date, dtype: datetime64[ns]

In [52]:
time = pd.read_csv('/content/messages.csv')   # Google Colab

In [53]:
# Converting to datetime datatype
time['date'] = pd.to_datetime(time['date'])

In [54]:
time.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   date    1000 non-null   datetime64[ns]
 1   msg     1000 non-null   object
dtypes: datetime64[ns](1), object(1)
memory usage: 15.8+ KB

In [55]:
time['hour'] = time['date'].dt.hour
time['min'] = time['date'].dt.minute
time['sec'] = time['date'].dt.second

time.head()

,date,msg,hour,min,sec
0,2013-12-15 00:50:00,ищу на сегодня мужика 37,0,50,0
1,2014-04-29 23:40:00,ПАРЕНЬ БИ ИЩЕТ ДРУГА СЕЙЧАС!! СМС ММС 0955532826,23,40,0
2,2012-12-30 00:21:00,Днепр.м 43 позн.с д/ж *.о 067.16.34.576,0,21,0
3,2014-11-28 00:31:00,КИЕВ ИЩУ Д/Ж ДО 45 МНЕ СЕЙЧАС СКУЧНО 093 629 9...,0,31,0
4,2013-10-26 23:11:00,Зая я тебя никогда не обижу люблю тебя!) Даше,23,11,0

In [56]:
time['time'] = time['date'].dt.time

time.head()

,date,msg,hour,min,sec,time
0,2013-12-15 00:50:00,ищу на сегодня мужика 37,0,50,0,00:50:00
1,2014-04-29 23:40:00,ПАРЕНЬ БИ ИЩЕТ ДРУГА СЕЙЧАС!! СМС ММС 0955532826,23,40,0,23:40:00
2,2012-12-30 00:21:00,Днепр.м 43 позн.с д/ж *.о 067.16.34.576,0,21,0,00:21:00
3,2014-11-28 00:31:00,КИЕВ ИЩУ Д/Ж ДО 45 МНЕ СЕЙЧАС СКУЧНО 093 629 9...,0,31,0,00:31:00
4,2013-10-26 23:11:00,Зая я тебя никогда не обижу люблю тебя!) Даше,23,11,0,23:11:00

In [57]:
today - time['date']

0     4608 days 18:30:51.966134
1     4472 days 19:40:51.966134
2     4958 days 18:59:51.966134
3     4260 days 18:49:51.966134
4     4657 days 20:09:51.966134
                 ...
995   5247 days 18:30:51.966134
996   4568 days 20:06:51.966134
997   5033 days 19:43:51.966134
998   5149 days 19:46:51.966134
999   4421 days 19:55:51.966134
Name: date, Length: 1000, dtype: timedelta64[ns]

In [58]:
(today - time['date'])/np.timedelta64(1,'m')

0      6.636631e+06
1      6.440861e+06
2      7.140660e+06
3      6.135530e+06
4      6.707290e+06
           ...
995    7.556791e+06
996    6.579127e+06
997    7.248704e+06
998    7.415747e+06
999    6.367436e+06
Name: date, Length: 1000, dtype: float64

In [59]:

(today - time['date'])/np.timedelta64(1,'s')

0      3.981979e+08
1      3.864517e+08
2      4.284396e+08
3      3.681318e+08
4      4.024374e+08
           ...
995    4.534075e+08
996    3.947476e+08
997    4.349222e+08
998    4.449448e+08
999    3.820462e+08
Name: date, Length: 1000, dtype: float64

In [60]:

(today - time['date'])/np.timedelta64(1,'h')

0      110610.514435
1      107347.681102
2      119010.997768
3      102258.831102
4      111788.164435
           ...
995    125946.514435
996    109652.114435
997    120811.731102
998    123595.781102
999    106123.931102
Name: date, Length: 1000, dtype: float64